agents:
  queue: nsc-artifact-storage

common:
  - zipstash_pkg_plugin: &zstash-ruby
      buildkite/zstash#main:
        id: "ruby-nsc"
        key: '{{ id }}-{{ agent.os }}-{{ agent.arch }}-{{ checksum "Gemfile.lock" }}'
        fallback_keys: |
          {{ id }}-{{ agent.os }}-{{ agent.arch }}-
        paths: |
          vendor/bundle
        bucket-url: $BUCKET_URL
        store: "nsc"

env:
  BUNDLE_FROZEN: true # Don't allow lockfile to mutate during CI
  BUNDLE_PATH: vendor/bundle

steps:
  - group: "Without Buildkite Cache"
    steps:
      - label: ":rubygems: :rspec: Run system specs"
        command:
          - "bundle install --quiet"
          - "bundle exec rspec spec/system"
      - label: ":rubygems: :rspec: Run model specs"
        command:
          - "bundle install --quiet"
          - "bundle exec rspec spec/models"
  - group: "With Buildkite Cache"
    steps:
      - label: ":rubygems: Install dependencies"
        key: "install_dependencies"
        command:
          - "bundle install --quiet"
        plugins:
          - *zstash-ruby
      - label: ":rspec: Run system specs"
        command:
          - "bundle exec rspec spec/system"
        depends_on:
          - "install_dependencies"
        plugins:
          - *zstash-ruby
      - label: ":rspec: Run model specs"
        command:
          - "bundle exec rspec spec/models"
        depends_on:
          - "install_dependencies"
        plugins:
          - *zstash-ruby
