common:
  - aws-assume-role_plugin: &aws-assume-role
      aws-assume-role-with-web-identity#v1.1.0:
        role-arn: ${CACHE_ROLE}
  - buildkite_cache_ruby: &buildkite-cache-ruby-and-docker
      "buildkite/zstash":
        ids: "ruby,docker"
        config: ".buildkite/cache.elastic.yml"
  - buildkite_cache_docker: &buildkite-cache-docker
      "buildkite/zstash":
        ids: "docker"
        config: ".buildkite/cache.elastic.yml"
  -  docker-compose_plugin: &docker-compose
      docker-compose#v5.10.0:
        config: .buildkite/docker-compose.yaml
        run: ruby
        tty: true
        mount-buildkite-agent: true
  - docker-compose_plugin: &docker-compose-build
      docker-compose#v5.10.0:
        config: .buildkite/docker-compose.yaml
        build: ruby
        builder:
          name: container
          driver: docker-container
          create: true
          use: true
        progress: plain
        cache-from:
          - "ruby:type=local,src=vendor/containers,compression=uncompressed"
        cache-to:
          - "ruby:type=local,dest=vendor/containers,compression=uncompressed"

env:
  BUNDLE_FROZEN: true # Don't allow lockfile to mutate during CI

steps:
  - group: "Without Buildkite Cache"
    steps:
      - label: ":rubygems: :rspec: Run system specs"
        command:
          - "bundle install --frozen --quiet --path vendor/bundle"
          - "bundle exec rspec spec/system"
        plugins:
          - *docker-compose
      - label: ":rubygems: :rspec: Run model specs"
        command:
          - "bundle config --local path vendor/bundle"
          - "bundle config --local frozen true"
          - "bundle config --local quiet true"
          - "bundle install"
          - "bundle exec rspec spec/models"
        plugins:
          - *docker-compose
  - group: "With Buildkite Cache"
    steps:
      - label: ":docker: Build base image"
        key: "build_base_image"
        plugins:
          - *aws-assume-role
          - *buildkite-cache-docker
          - *docker-compose-build
      - label: ":rubygems: Install dependencies"
        key: "install_dependencies"
        depends_on:
          - "build_base_image"
        command:
          - "bundle config --local path vendor/bundle"
          - "bundle config --local frozen true"
          - "bundle config --local quiet true"
          - "bundle install"
        plugins:
          - *aws-assume-role
          - *buildkite-cache-ruby-and-docker
          - *docker-compose-build
          - *docker-compose
      - label: ":rspec: Run system specs"
        command:
          - "bundle config --local path vendor/bundle"
          - "bundle exec rspec spec/system"
        depends_on:
          - "install_dependencies"
        plugins:
          - *aws-assume-role
          - *buildkite-cache-ruby-and-docker
          - *docker-compose-build
          - *docker-compose
      - label: ":rspec: Run model specs"
        command:
          - "bundle config --local path vendor/bundle"
          - "bundle exec rspec spec/models"
        depends_on:
          - "install_dependencies"
        plugins:
          - *aws-assume-role
          - *buildkite-cache-ruby-and-docker
          - *docker-compose-build
          - *docker-compose
