common:
  - aws-assume-role_plugin: &aws-assume-role
      aws-assume-role-with-web-identity#v1.1.0:
        role-arn: ${CACHE_ROLE}
  - zipstash_pkg_plugin: &zstash-ruby
      buildkite/zstash#v0.1.0:
        id: "ruby-2"
        key: '{{ id }}-{{ agent.os }}-{{ agent.arch }}-{{ checksum "Gemfile.lock" }}'
        fallback_keys: |
          {{ id }}-{{ agent.os }}-{{ agent.arch }}-
        paths: |
          vendor/bundle
        bucket-url: $BUCKET_URL
  -  docker-compose_plugin: &docker-compose
      docker-compose#v5.2.0:
        config: .buildkite/docker-compose.yaml
        run: ruby
        tty: true
        mount-buildkite-agent: true

steps:
  - group: "Without Buildkite Cache"
    steps:
      - label: ":rubygems: :rspec: Run system specs"
        command:
          - "bundle config --local path vendor/bundle"
          - "bundle install"
          - "bundle exec rspec spec/system"
        plugins:
          - *docker-compose
      - label: ":rubygems: :rspec: Run model specs"
        command:
          - "bundle config --local path vendor/bundle"
          - "bundle install"
          - "bundle exec rspec spec/models"
        plugins:
          - *docker-compose
  - group: "With Buildkite Cache"
    steps:
      - label: ":rubygems: Install dependencies"
        key: "install_dependencies"
        command:
          - "bundle config --local path vendor/bundle"
          - "bundle install"
        plugins:
          - *docker-compose
          - *aws-assume-role
          - *zstash-ruby
      - label: ":rspec: Run system specs"
        command: "bundle exec rspec spec/system"
        depends_on:
          - "install_dependencies"
        plugins:
          - *docker-compose
          - *aws-assume-role
          - *zstash-ruby
      - label: ":rspec: Run model specs"
        command: "bundle exec rspec spec/models"
        depends_on:
          - "install_dependencies"
        plugins:
          - *docker-compose
          - *aws-assume-role
          - *zstash-ruby
