agents:
  queue: nsc-artifact-storage

common:
  - buildkite_cache: &buildkite-cache
      "buildkite/zstash":
        ids: "ruby_1,docker_1"
        config: ".buildkite/cache.hosted.yml"

env:
  BUNDLE_FROZEN: true # Don't allow lockfile to mutate during CI
  BUNDLE_PATH: vendor/bundle

steps:
  - group: "Without Buildkite Cache"
    steps:
      - label: ":rubygems: :rspec: Run system specs"
        command:
          - "bundle install --quiet"
          - "bundle exec rspec spec/system"
      - label: ":rubygems: :rspec: Run model specs"
        command:
          - "bundle install --quiet"
          - "bundle exec rspec spec/models"
  - group: "With Buildkite Cache"
    steps:
      - label: ":rubygems: Install dependencies"
        key: "install_dependencies"
        command:
          - "bundle install --quiet"
        plugins:
          - *buildkite-cache
      - label: ":rspec: Run system specs"
        command:
          - "bundle exec rspec spec/system"
        depends_on:
          - "install_dependencies"
        plugins:
          - *buildkite-cache
      - label: ":rspec: Run model specs"
        command:
          - "bundle exec rspec spec/models"
        depends_on:
          - "install_dependencies"
        plugins:
          - *buildkite-cache
